version: '2'

volumes:
    volume_1:

services:
  sensor:
    build: ./sensor
    restart: no
    privileged: true

  telegraf:
    build: ./telegraf
    restart: no
    cap_add:
      - SYS_ADMIN

  influxdb:
    build: ./influxdb
    restart: no
    volumes:
      - 'volume_1:/data'

  grafana:
    restart: no
    build: ./grafana
    ports:
      - '80'
    volumes:
      - 'volume_1:/data'
    environment:
      - 'GF_SERVER_HTTP_PORT=80'
      - 'GF_PATHS_PROVISIONING=/usr/src/app/provisioning'
      - 'GF_SESSION_PROVIDER=memory'
